# Site settings
title: Your awesome title
email: root@metafour.org
description: > # this means to ignore newlines until "baseurl:"
  development blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metafour.org" # the base hostname & protocol for your site
twitter_username: metafour
github_username:  metafour

# Build settings
markdown: kramdown
highlighter: rouge
